### ISSUE TITLE
使用的时候，undo.js里报错。

### ISSUE THREAD

**Issue by yuanyuan821** [jzaefferer/undo#8]
undo: function() {
		this.commands[this.stackPosition].undo();
//说这里的undo()未定义
		this.stackPosition--;
		this.changed();
	},
redo: function() {
		this.stackPosition++;
		this.commands[this.stackPosition].redo();
//还有这里的redo()，也是未定义
		this.changed();
	},

**Comment by Michael18811380328** [comment]
这个代码好几年没更新了

**Comment by jzaefferer** [comment]
No idea what that means
